services:
  - type: web
    name: emvid
    env: python
    rootDir: backend
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:asgi_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://..."
      - key: JWT_SECRET_KEY
        value: "723957c73e4561efe45d0d8a81b7d0b0"
      - key: JWT_ALGORITHM
        value: "HS256"

  - type: web
    name: emvid-frontend
    env: node
    nodeVersion: "20"
    rootDir: frontend
    buildCommand: |
      npm install -g pnpm
      pnpm install --frozen-lockfile
      pnpm run build
    staticPublishPath: build
    envVars:
      - key: VITE_API_URL
        value: https://emvid.onrender.com
      - key: VITE_WEBSOCKET_URL
        value: wss://emvid.onrender.com/ws
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
